CLASS zc_rap_journalreq_c DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZC_RAP_JOURNALREQ_C IMPLEMENTATION.


  METHOD if_oo_adt_classrun~main.
  ENDMETHOD.
ENDCLASS.
